-- =============================================================================
-- VitalWatch - Apache Kafka Integration
-- Script de Creación de Tablas para Oracle Cloud Database
-- =============================================================================
-- Base de Datos: Oracle Autonomous Database
-- Service: s58onuxcx4c1qxe9_high
-- Región: Santiago, Chile
-- =============================================================================

-- =============================================================================
-- TABLA: SIGNOS_VITALES_KAFKA
-- Almacena el stream continuo de signos vitales de pacientes
-- =============================================================================

CREATE TABLE SIGNOS_VITALES_KAFKA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Información del mensaje Kafka
    kafka_topic VARCHAR2(100) NOT NULL,
    kafka_partition NUMBER NOT NULL,
    kafka_offset NUMBER NOT NULL,
    kafka_timestamp TIMESTAMP NOT NULL,
    
    -- Identificación del paciente
    paciente_id VARCHAR2(50) NOT NULL,
    paciente_nombre VARCHAR2(200) NOT NULL,
    sala VARCHAR2(50),
    cama VARCHAR2(20),
    
    -- Signos vitales
    frecuencia_cardiaca NUMBER(3) CHECK (frecuencia_cardiaca >= 0 AND frecuencia_cardiaca <= 300),
    presion_sistolica NUMBER(3) CHECK (presion_sistolica >= 0 AND presion_sistolica <= 300),
    presion_diastolica NUMBER(3) CHECK (presion_diastolica >= 0 AND presion_diastolica <= 200),
    temperatura NUMBER(4,2) CHECK (temperatura >= 30.0 AND temperatura <= 45.0),
    saturacion_oxigeno NUMBER(3) CHECK (saturacion_oxigeno >= 0 AND saturacion_oxigeno <= 100),
    frecuencia_respiratoria NUMBER(3) CHECK (frecuencia_respiratoria >= 0 AND frecuencia_respiratoria <= 60),
    
    -- Identificación del dispositivo
    device_id VARCHAR2(50),
    
    -- Metadatos
    timestamp_medicion TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    -- Constraints
    CONSTRAINT uq_kafka_message UNIQUE (kafka_topic, kafka_partition, kafka_offset)
);

-- Índices para optimizar consultas
CREATE INDEX idx_sv_kafka_paciente ON SIGNOS_VITALES_KAFKA(paciente_id, timestamp_medicion DESC);
CREATE INDEX idx_sv_kafka_timestamp ON SIGNOS_VITALES_KAFKA(timestamp_medicion DESC);
CREATE INDEX idx_sv_kafka_sala ON SIGNOS_VITALES_KAFKA(sala, timestamp_medicion DESC);
CREATE INDEX idx_sv_kafka_device ON SIGNOS_VITALES_KAFKA(device_id, timestamp_medicion DESC);
CREATE INDEX idx_sv_kafka_offset ON SIGNOS_VITALES_KAFKA(kafka_partition, kafka_offset);

-- Comentarios
COMMENT ON TABLE SIGNOS_VITALES_KAFKA IS 'Stream de signos vitales en tiempo real desde Kafka';
COMMENT ON COLUMN SIGNOS_VITALES_KAFKA.kafka_partition IS 'Partición de Kafka de donde provino el mensaje';
COMMENT ON COLUMN SIGNOS_VITALES_KAFKA.kafka_offset IS 'Offset del mensaje en Kafka para trazabilidad';

-- =============================================================================
-- TABLA: ALERTAS_KAFKA
-- Almacena alertas médicas detectadas por el Alert Processor
-- =============================================================================

CREATE TABLE ALERTAS_KAFKA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Información del mensaje Kafka
    kafka_topic VARCHAR2(100) NOT NULL,
    kafka_partition NUMBER NOT NULL,
    kafka_offset NUMBER NOT NULL,
    kafka_timestamp TIMESTAMP NOT NULL,
    
    -- Identificación única de la alerta
    alert_id VARCHAR2(100) UNIQUE NOT NULL,
    
    -- Información del paciente
    paciente_id VARCHAR2(50) NOT NULL,
    paciente_nombre VARCHAR2(200) NOT NULL,
    sala VARCHAR2(50),
    cama VARCHAR2(20),
    
    -- Detalles de la alerta
    tipo_alerta VARCHAR2(100) NOT NULL,
    mensaje CLOB NOT NULL,
    severidad VARCHAR2(20) NOT NULL CHECK (severidad IN ('BAJA', 'MODERADA', 'ALTA', 'CRITICA')),
    
    -- Signos vitales que causaron la alerta
    frecuencia_cardiaca NUMBER(3),
    presion_sistolica NUMBER(3),
    presion_diastolica NUMBER(3),
    temperatura NUMBER(4,2),
    saturacion_oxigeno NUMBER(3),
    frecuencia_respiratoria NUMBER(3),
    
    -- Anomalías detectadas (JSON)
    anomalias CLOB CHECK (anomalias IS JSON),
    cantidad_anomalias NUMBER DEFAULT 0,
    
    -- Identificación del dispositivo
    device_id VARCHAR2(50),
    
    -- Estado de la alerta
    estado VARCHAR2(20) DEFAULT 'ACTIVA' CHECK (estado IN ('ACTIVA', 'EN_REVISION', 'RESUELTA', 'DESCARTADA')),
    fecha_resolucion TIMESTAMP,
    resuelto_por VARCHAR2(100),
    notas_resolucion VARCHAR2(1000),
    
    -- Timestamps
    detected_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    -- Constraints
    CONSTRAINT uq_kafka_alert_message UNIQUE (kafka_topic, kafka_partition, kafka_offset)
);

-- Índices para optimizar consultas
CREATE INDEX idx_alertas_kafka_paciente ON ALERTAS_KAFKA(paciente_id, detected_at DESC);
CREATE INDEX idx_alertas_kafka_severidad ON ALERTAS_KAFKA(severidad, estado, detected_at DESC);
CREATE INDEX idx_alertas_kafka_estado ON ALERTAS_KAFKA(estado, detected_at DESC);
CREATE INDEX idx_alertas_kafka_timestamp ON ALERTAS_KAFKA(detected_at DESC);
CREATE INDEX idx_alertas_kafka_device ON ALERTAS_KAFKA(device_id, detected_at DESC);
CREATE INDEX idx_alertas_kafka_alert_id ON ALERTAS_KAFKA(alert_id);

-- Comentarios
COMMENT ON TABLE ALERTAS_KAFKA IS 'Alertas médicas procesadas desde stream de Kafka';
COMMENT ON COLUMN ALERTAS_KAFKA.alert_id IS 'Identificador único de la alerta generado por el productor';
COMMENT ON COLUMN ALERTAS_KAFKA.anomalias IS 'JSON con detalles de cada anomalía detectada';

-- =============================================================================
-- TABLA: RESUMEN_DIARIO_KAFKA
-- Resúmenes agregados diarios del sistema de monitoreo
-- =============================================================================

CREATE TABLE RESUMEN_DIARIO_KAFKA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Fecha del resumen
    fecha DATE NOT NULL UNIQUE,
    
    -- Estadísticas de pacientes
    total_pacientes_monitoreados NUMBER DEFAULT 0,
    pacientes_con_alertas NUMBER DEFAULT 0,
    
    -- Estadísticas de mediciones
    total_mediciones NUMBER DEFAULT 0,
    mediciones_por_hora NUMBER(10,2) DEFAULT 0,
    
    -- Estadísticas de alertas
    total_alertas NUMBER DEFAULT 0,
    alertas_criticas NUMBER DEFAULT 0,
    alertas_altas NUMBER DEFAULT 0,
    alertas_moderadas NUMBER DEFAULT 0,
    alertas_bajas NUMBER DEFAULT 0,
    
    -- Promedios de signos vitales
    promedio_frecuencia_cardiaca NUMBER(5,2),
    promedio_presion_sistolica NUMBER(5,2),
    promedio_presion_diastolica NUMBER(5,2),
    promedio_temperatura NUMBER(4,2),
    promedio_saturacion_oxigeno NUMBER(5,2),
    promedio_frecuencia_respiratoria NUMBER(5,2),
    
    -- Valores extremos del día
    max_frecuencia_cardiaca NUMBER(3),
    min_frecuencia_cardiaca NUMBER(3),
    max_temperatura NUMBER(4,2),
    min_temperatura NUMBER(4,2),
    min_saturacion_oxigeno NUMBER(3),
    
    -- Información de Kafka
    mensajes_procesados_vital_signs NUMBER DEFAULT 0,
    mensajes_procesados_alertas NUMBER DEFAULT 0,
    
    -- Metadatos
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ultima_actualizacion TIMESTAMP,
    
    -- Constraints
    CONSTRAINT chk_fecha_valida CHECK (fecha <= TRUNC(SYSDATE) + 1)
);

-- Índices
CREATE INDEX idx_resumen_fecha ON RESUMEN_DIARIO_KAFKA(fecha DESC);
CREATE INDEX idx_resumen_created ON RESUMEN_DIARIO_KAFKA(created_at DESC);

-- Comentarios
COMMENT ON TABLE RESUMEN_DIARIO_KAFKA IS 'Resúmenes diarios agregados del sistema de streaming';
COMMENT ON COLUMN RESUMEN_DIARIO_KAFKA.mensajes_procesados_vital_signs IS 'Total de mensajes del tópico signos-vitales-stream';
COMMENT ON COLUMN RESUMEN_DIARIO_KAFKA.mensajes_procesados_alertas IS 'Total de mensajes del tópico alertas-medicas';

-- =============================================================================
-- TABLA: PACIENTES_MONITOREADOS_KAFKA
-- Catálogo de pacientes monitoreados en el sistema
-- =============================================================================

CREATE TABLE PACIENTES_MONITOREADOS_KAFKA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Identificación
    paciente_id VARCHAR2(50) UNIQUE NOT NULL,
    paciente_nombre VARCHAR2(200) NOT NULL,
    
    -- Ubicación
    sala VARCHAR2(50),
    cama VARCHAR2(20),
    
    -- Dispositivos asignados
    device_id VARCHAR2(50),
    
    -- Estado
    estado VARCHAR2(20) DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'INACTIVO', 'DADO_DE_ALTA')),
    
    -- Estadísticas
    total_mediciones NUMBER DEFAULT 0,
    ultima_medicion TIMESTAMP,
    total_alertas NUMBER DEFAULT 0,
    ultima_alerta TIMESTAMP,
    
    -- Timestamps
    fecha_ingreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_alta TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Índices
CREATE INDEX idx_pacientes_kafka_id ON PACIENTES_MONITOREADOS_KAFKA(paciente_id);
CREATE INDEX idx_pacientes_kafka_estado ON PACIENTES_MONITOREADOS_KAFKA(estado, ultima_medicion DESC);
CREATE INDEX idx_pacientes_kafka_sala ON PACIENTES_MONITOREADOS_KAFKA(sala, cama);

-- Comentarios
COMMENT ON TABLE PACIENTES_MONITOREADOS_KAFKA IS 'Catálogo de pacientes en el sistema de streaming';

-- =============================================================================
-- VISTAS ÚTILES PARA CONSULTAS
-- =============================================================================

-- Vista: Últimas mediciones por paciente
CREATE OR REPLACE VIEW V_ULTIMAS_MEDICIONES_KAFKA AS
SELECT 
    p.paciente_id,
    p.paciente_nombre,
    p.sala,
    p.cama,
    sv.frecuencia_cardiaca,
    sv.presion_sistolica,
    sv.presion_diastolica,
    sv.temperatura,
    sv.saturacion_oxigeno,
    sv.frecuencia_respiratoria,
    sv.timestamp_medicion,
    sv.device_id,
    RANK() OVER (PARTITION BY p.paciente_id ORDER BY sv.timestamp_medicion DESC) as rn
FROM PACIENTES_MONITOREADOS_KAFKA p
LEFT JOIN SIGNOS_VITALES_KAFKA sv ON p.paciente_id = sv.paciente_id
WHERE p.estado = 'ACTIVO';

-- Vista: Alertas activas por severidad
CREATE OR REPLACE VIEW V_ALERTAS_ACTIVAS_KAFKA AS
SELECT 
    severidad,
    COUNT(*) as total_alertas,
    COUNT(DISTINCT paciente_id) as pacientes_afectados,
    MIN(detected_at) as alerta_mas_antigua,
    MAX(detected_at) as alerta_mas_reciente
FROM ALERTAS_KAFKA
WHERE estado = 'ACTIVA'
GROUP BY severidad
ORDER BY 
    CASE severidad
        WHEN 'CRITICA' THEN 1
        WHEN 'ALTA' THEN 2
        WHEN 'MODERADA' THEN 3
        WHEN 'BAJA' THEN 4
    END;

-- Vista: Estadísticas en tiempo real
CREATE OR REPLACE VIEW V_ESTADISTICAS_TIEMPO_REAL_KAFKA AS
SELECT 
    COUNT(DISTINCT paciente_id) as pacientes_activos,
    COUNT(*) as total_mediciones_hoy,
    ROUND(AVG(frecuencia_cardiaca), 2) as avg_fc,
    ROUND(AVG(temperatura), 2) as avg_temp,
    ROUND(AVG(saturacion_oxigeno), 2) as avg_spo2,
    MAX(timestamp_medicion) as ultima_medicion
FROM SIGNOS_VITALES_KAFKA
WHERE TRUNC(timestamp_medicion) = TRUNC(SYSDATE);

-- =============================================================================
-- TRIGGERS PARA ACTUALIZACIÓN AUTOMÁTICA
-- =============================================================================

-- Trigger: Actualizar updated_at en ALERTAS_KAFKA
CREATE OR REPLACE TRIGGER trg_alertas_kafka_updated
BEFORE UPDATE ON ALERTAS_KAFKA
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Trigger: Actualizar updated_at en PACIENTES_MONITOREADOS_KAFKA
CREATE OR REPLACE TRIGGER trg_pacientes_kafka_updated
BEFORE UPDATE ON PACIENTES_MONITOREADOS_KAFKA
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Trigger: Actualizar estadísticas de paciente al insertar medición
CREATE OR REPLACE TRIGGER trg_actualizar_stats_paciente
AFTER INSERT ON SIGNOS_VITALES_KAFKA
FOR EACH ROW
BEGIN
    UPDATE PACIENTES_MONITOREADOS_KAFKA
    SET 
        total_mediciones = total_mediciones + 1,
        ultima_medicion = :NEW.timestamp_medicion,
        updated_at = CURRENT_TIMESTAMP
    WHERE paciente_id = :NEW.paciente_id;
    
    -- Si el paciente no existe, insertarlo
    IF SQL%ROWCOUNT = 0 THEN
        INSERT INTO PACIENTES_MONITOREADOS_KAFKA (
            paciente_id, 
            paciente_nombre, 
            sala, 
            cama, 
            device_id,
            total_mediciones,
            ultima_medicion
        ) VALUES (
            :NEW.paciente_id,
            :NEW.paciente_nombre,
            :NEW.sala,
            :NEW.cama,
            :NEW.device_id,
            1,
            :NEW.timestamp_medicion
        );
    END IF;
END;
/

-- Trigger: Actualizar estadísticas de paciente al insertar alerta
CREATE OR REPLACE TRIGGER trg_actualizar_stats_alerta
AFTER INSERT ON ALERTAS_KAFKA
FOR EACH ROW
BEGIN
    UPDATE PACIENTES_MONITOREADOS_KAFKA
    SET 
        total_alertas = total_alertas + 1,
        ultima_alerta = :NEW.detected_at,
        updated_at = CURRENT_TIMESTAMP
    WHERE paciente_id = :NEW.paciente_id;
END;
/

-- =============================================================================
-- DATOS INICIALES DE PRUEBA
-- =============================================================================

-- Insertar pacientes de prueba
INSERT INTO PACIENTES_MONITOREADOS_KAFKA (paciente_id, paciente_nombre, sala, cama, device_id, estado)
VALUES ('P001', 'Juan Pérez', 'UCI-A', '101', 'DEVICE-001', 'ACTIVO');

INSERT INTO PACIENTES_MONITOREADOS_KAFKA (paciente_id, paciente_nombre, sala, cama, device_id, estado)
VALUES ('P002', 'María García', 'UCI-A', '102', 'DEVICE-002', 'ACTIVO');

INSERT INTO PACIENTES_MONITOREADOS_KAFKA (paciente_id, paciente_nombre, sala, cama, device_id, estado)
VALUES ('P003', 'Carlos López', 'UCI-B', '201', 'DEVICE-003', 'ACTIVO');

INSERT INTO PACIENTES_MONITOREADOS_KAFKA (paciente_id, paciente_nombre, sala, cama, device_id, estado)
VALUES ('P004', 'Ana Martínez', 'UCI-B', '202', 'DEVICE-004', 'ACTIVO');

INSERT INTO PACIENTES_MONITOREADOS_KAFKA (paciente_id, paciente_nombre, sala, cama, device_id, estado)
VALUES ('P005', 'Pedro Sánchez', 'UCI-C', '301', 'DEVICE-005', 'ACTIVO');

COMMIT;

-- =============================================================================
-- QUERIES ÚTILES PARA MONITOREO
-- =============================================================================

-- Ver últimas 10 mediciones
-- SELECT * FROM SIGNOS_VITALES_KAFKA ORDER BY timestamp_medicion DESC FETCH FIRST 10 ROWS ONLY;

-- Ver alertas activas críticas
-- SELECT * FROM ALERTAS_KAFKA WHERE estado = 'ACTIVA' AND severidad = 'CRITICA' ORDER BY detected_at DESC;

-- Ver resumen del día actual
-- SELECT * FROM RESUMEN_DIARIO_KAFKA WHERE fecha = TRUNC(SYSDATE);

-- Ver pacientes activos con sus últimas mediciones
-- SELECT * FROM V_ULTIMAS_MEDICIONES_KAFKA WHERE rn = 1;

-- Ver estadísticas en tiempo real
-- SELECT * FROM V_ESTADISTICAS_TIEMPO_REAL_KAFKA;

-- =============================================================================
-- FIN DEL SCRIPT
-- =============================================================================

PROMPT 'Tablas de Kafka creadas exitosamente';
PROMPT 'Total de tablas: 4';
PROMPT 'Total de vistas: 3';
PROMPT 'Total de triggers: 4';
PROMPT 'Pacientes de prueba: 5';
