-- ============================================================================
-- VitalWatch - Script de Creación de Tabla ALERTAS_MQ
-- Base de Datos: Oracle Autonomous Database (OCI)
-- Propósito: Almacenar alertas de signos vitales recibidas desde RabbitMQ
-- ============================================================================

-- Eliminar tabla si existe (solo para desarrollo/testing)
-- DESCOMENTAR SOLO SI NECESITAS RECREAR LA TABLA
-- DROP TABLE ALERTAS_MQ CASCADE CONSTRAINTS;
-- DROP SEQUENCE SEQ_ALERTAS_MQ;

-- ============================================================================
-- Crear Secuencia para IDs
-- ============================================================================
CREATE SEQUENCE SEQ_ALERTAS_MQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ============================================================================
-- Crear Tabla ALERTAS_MQ
-- ============================================================================
CREATE TABLE ALERTAS_MQ (
    -- Identificador único de la alerta
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    
    -- Información del Paciente
    PACIENTE_ID NUMBER NOT NULL,
    PACIENTE_NOMBRE VARCHAR2(100) NOT NULL,
    SALA VARCHAR2(50) NOT NULL,
    CAMA VARCHAR2(50) NOT NULL,
    
    -- Detalles de las Anomalías
    ANOMALIAS_JSON CLOB NOT NULL,  -- JSON con array de anomalías detectadas
    ANOMALIAS_COUNT NUMBER NOT NULL,  -- Cantidad de anomalías
    SEVERITY VARCHAR2(20) NOT NULL,  -- CRITICA, ALTA, MEDIA
    
    -- Signos Vitales al momento de la alerta
    FRECUENCIA_CARDIACA NUMBER,
    PRESION_SISTOLICA NUMBER,
    PRESION_DIASTOLICA NUMBER,
    TEMPERATURA VARCHAR2(10),
    SATURACION_OXIGENO NUMBER,
    FRECUENCIA_RESPIRATORIA NUMBER,
    
    -- Información Técnica
    DEVICE_ID VARCHAR2(100),  -- ID del dispositivo médico que generó la alerta
    DETECTED_AT TIMESTAMP NOT NULL,  -- Momento de detección
    SAVED_AT TIMESTAMP NOT NULL,  -- Momento de guardado en BD
    QUEUE_NAME VARCHAR2(100) NOT NULL,  -- Nombre de la cola de RabbitMQ
    
    -- Constraints
    CONSTRAINT CHK_SEVERITY CHECK (SEVERITY IN ('CRITICA', 'ALTA', 'MEDIA', 'BAJA')),
    CONSTRAINT CHK_ANOMALIAS_COUNT CHECK (ANOMALIAS_COUNT > 0)
);

-- ============================================================================
-- Crear Índices para Mejorar Performance
-- ============================================================================

-- Índice por paciente (búsquedas frecuentes por paciente)
CREATE INDEX IDX_ALERTAS_PACIENTE ON ALERTAS_MQ(PACIENTE_ID);

-- Índice por severidad (filtrar alertas críticas)
CREATE INDEX IDX_ALERTAS_SEVERITY ON ALERTAS_MQ(SEVERITY);

-- Índice por fecha de detección (consultas por rango de fechas)
CREATE INDEX IDX_ALERTAS_DETECTED ON ALERTAS_MQ(DETECTED_AT DESC);

-- Índice compuesto para búsquedas por paciente y fecha
CREATE INDEX IDX_ALERTAS_PAC_FECHA ON ALERTAS_MQ(PACIENTE_ID, DETECTED_AT DESC);

-- Índice por sala (búsquedas por ubicación)
CREATE INDEX IDX_ALERTAS_SALA ON ALERTAS_MQ(SALA);

-- ============================================================================
-- Crear Trigger para Actualización Automática de SAVED_AT
-- ============================================================================
CREATE OR REPLACE TRIGGER TRG_ALERTAS_SAVED_AT
BEFORE INSERT OR UPDATE ON ALERTAS_MQ
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :NEW.SAVED_AT := SYSTIMESTAMP;
    END IF;
END;
/

-- ============================================================================
-- Comentarios en la Tabla y Columnas
-- ============================================================================
COMMENT ON TABLE ALERTAS_MQ IS 'Alertas de signos vitales anómalos recibidas desde RabbitMQ';

COMMENT ON COLUMN ALERTAS_MQ.ID IS 'Identificador único de la alerta';
COMMENT ON COLUMN ALERTAS_MQ.PACIENTE_ID IS 'ID del paciente relacionado';
COMMENT ON COLUMN ALERTAS_MQ.PACIENTE_NOMBRE IS 'Nombre completo del paciente';
COMMENT ON COLUMN ALERTAS_MQ.SALA IS 'Sala donde se encuentra el paciente';
COMMENT ON COLUMN ALERTAS_MQ.CAMA IS 'Número de cama del paciente';
COMMENT ON COLUMN ALERTAS_MQ.ANOMALIAS_JSON IS 'Array JSON con detalles de cada anomalía detectada';
COMMENT ON COLUMN ALERTAS_MQ.ANOMALIAS_COUNT IS 'Cantidad total de anomalías en esta alerta';
COMMENT ON COLUMN ALERTAS_MQ.SEVERITY IS 'Nivel de severidad: CRITICA, ALTA, MEDIA, BAJA';
COMMENT ON COLUMN ALERTAS_MQ.DETECTED_AT IS 'Timestamp de detección de la anomalía';
COMMENT ON COLUMN ALERTAS_MQ.SAVED_AT IS 'Timestamp de guardado en la base de datos';
COMMENT ON COLUMN ALERTAS_MQ.QUEUE_NAME IS 'Nombre de la cola RabbitMQ de origen';

-- ============================================================================
-- Conceder Permisos (ajustar según sea necesario)
-- ============================================================================
-- Si tienes otros usuarios que necesitan acceso:
-- GRANT SELECT, INSERT ON ALERTAS_MQ TO [usuario];
-- GRANT SELECT ON SEQ_ALERTAS_MQ TO [usuario];

-- ============================================================================
-- Verificación de Creación
-- ============================================================================
SELECT 'Tabla ALERTAS_MQ creada exitosamente' AS STATUS FROM DUAL;
SELECT COUNT(*) AS TOTAL_ALERTAS FROM ALERTAS_MQ;

-- ============================================================================
-- Consultas Útiles para Verificación y Monitoreo
-- ============================================================================

-- Ver estructura de la tabla
-- DESC ALERTAS_MQ;

-- Ver índices creados
-- SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION 
-- FROM USER_IND_COLUMNS 
-- WHERE TABLE_NAME = 'ALERTAS_MQ'
-- ORDER BY INDEX_NAME, COLUMN_POSITION;

-- Ver últimas 10 alertas
-- SELECT ID, PACIENTE_ID, PACIENTE_NOMBRE, SEVERITY, ANOMALIAS_COUNT, DETECTED_AT
-- FROM ALERTAS_MQ
-- ORDER BY DETECTED_AT DESC
-- FETCH FIRST 10 ROWS ONLY;

-- Contar alertas por severidad
-- SELECT SEVERITY, COUNT(*) AS TOTAL
-- FROM ALERTAS_MQ
-- GROUP BY SEVERITY
-- ORDER BY TOTAL DESC;

-- Alertas críticas de las últimas 24 horas
-- SELECT *
-- FROM ALERTAS_MQ
-- WHERE SEVERITY = 'CRITICA'
--   AND DETECTED_AT >= SYSTIMESTAMP - INTERVAL '24' HOUR
-- ORDER BY DETECTED_AT DESC;

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================
